from typing import Match
from manim import *
class FromulaThomson(Scene):
    def construct(self):
        eq1=MathTex('{{R}}\\cdot{{q}}\\cdot{{v}}\\cdot{{B}}={{m}}\\cdot{{v}}^2')
        eq2=MathTex('{{R}}\\cdot{{q}}\\cdot{{B}}={{m}}\\cdot{{v}}')
        self.play(Write(eq1))
        self.wait()
        self.play(TransformMatchingTex(eq1,eq2))
        self.wait()
        eq3=MathTex('Q=Ne')
        eq4=MathTex('2\\cdot W=N\\cdot m \\cdot v^2')
        eq5=MathTex('{{e}}\\cdot{{B}}^2\\cdot{{R}}^2\\cdot{{Q}}={{m}}\\cdot{{2}}\cdot{{W}}')
        eq3y4=VGroup(eq3,eq4).arrange(DOWN,buff=0.3)
        self.play(eq2.animate.to_edge(UP,buff=0.4),Write(eq3y4))
        self.wait()
        self.play(ReplacementTransform(VGroup(eq2,eq3y4),eq5))
        self.wait()
        eq6=MathTex('{{q}}\\cdot{{v}}\\cdot{{B}}={{q}}\\cdot{{\\varepsilon}}')
        eq7=MathTex('{{B}}\\cdot{{v}}={{\\varepsilon}}')
        self.play(eq5.animate.to_edge(UP,buff=.5),Write(eq6))
        self.wait()
        self.play(TransformMatchingTex(eq6,eq7))
        self.wait()
        eq8=MathTex('{{2}}\\cdot {{y_1}}={{a}}\cdot{{t_1}}^2')
        self.play(Write(eq8),eq7.animate.to_edge(DOWN))
        eq9=MathTex('{{2}}\\cdot{{y_1}}\\cdot{{m}}\\cdot{{v_x}}^2={{e}}\\cdot{{\\varepsilon}}\\cdot {{x_1}}^2')
        self.wait()
        self.play(TransformMatchingTex(eq8,eq9))
        self.wait()
        self.play(eq9.animate.move_to(2*UP))
        self.wait()
        eq10=MathTex('{{y_2}}={{v_y}}\\cdot{{t_2}}')
        eq11=MathTex('{{y_2}}\\cdot{{v_x}}={{a}}\cdot{{t_1}}\\cdot{{x_2}}')
        eq12=MathTex('{{y_2}}\\cdot{{m}}\\cdot{{v_x}}^2={{e}}\\cdot{{\\varepsilon}}\\cdot{{x_1}}\\cdot{{x_2}}')
        self.play(Write(eq10))
        self.wait()
        self.play(TransformMatchingTex(eq10,eq11))
        self.wait()
        self.play(TransformMatchingTex(eq11,eq12))
        self.wait()